// Section 0: Meta Rules — Reasoning-First & Anti-Hallucination
// Applies to ANY agent using this MCP server, regardless of editor / client.

export const SECTION_META_RULES = [
  "# Meta Rules — Reasoning & Anti-Hallucination",
  "",
  "> These two meta-rules apply to ANY agent using this MCP server, regardless of editor / client.",
  "> They take precedence over the workflow rules in the following sections.",
  ">",
  "> **Related top-level rule (domain, not agent behavior)**: For every UI control choice, the [Prime Directive — Standard Controls Before Custom](../../../docu/basics.md#§0-prime-directive-standard-controls-before-custom) in `basics.md` §0 governs the decision. The meta-rules govern *how* the agent reasons; the Prime Directive governs *what* it builds. Load `basics.md` §0 alongside these meta-rules for any task that touches widget / action / dialog / property-editor UI.",
  "",
  "## 🧠 Reasoning-First (before non-trivial work)",
  "",
  "Before generating or editing more than one file (or running any longer chain of tools), the agent MUST post a short reasoning message containing:",
  "",
  "1. **Understanding** of what the user wants (1–3 sentences)",
  "2. **Plan**: which files / tools, rough scope and effort",
  "3. **Open assumptions** (if any)",
  "",
  "Only then proceed with execution. Trivial reads/lookups do not require this preamble.",
  "",
  "**Why:** The user wants to see the agent's chain of thought BEFORE longer actions, not to discover surprising changes after the fact.",
  "",
  "## 📚 Source-or-Silence (no hallucination)",
  "",
  "**This MCP server is the SINGLE SOURCE OF TRUTH for POD2 / SAP DM specifics.** Training-data recall is treated as unreliable for anything framework-specific.",
  "",
  "### Authoritative sources by topic",
  "",
  "| Topic | Tools to use |",
  "|---|---|",
  "| POD2 API classes / methods / properties | `get_api_doc`, `search_api_docs`, `list_api_docs` |",
  "| POD2 patterns / conventions / lifecycle | `get_pattern_doc`, `search_docs` |",
  '| POD2 import paths (`sap/dm/dme/pod2/...`) | `get_api_doc`, `get_pattern_doc({ name: "deprecated-imports" })` |',
  "| SAP DM REST endpoints / DTOs | `get_rest_api`, `search_rest_apis`, `list_rest_apis` |",
  "| MDO entities / fields | `get_mdo_entity`, `search_mdo_entities` |",
  "| Example code / proven patterns | `get_example` |",
  "| Generic UI5 controls / properties / events | `search_ui5_api`, `get_ui5_api`, `list_ui5_libraries` |",
  "| Cross-cutting search | `search_all` |",
  "",
  "For **generic UI5** (`sap.m`, `sap.ui.core`, `sap.ui.layout`, `sap.f`, `sap.suite.ui.microchart`, `sap.suite.ui.commons`, `sap.chart`, `sap.tnt`, `sap.uxap`, `sap.ui.integration`, `sap.viz`, `sap.gantt`, …) use `pod2-mcp-server`'s `search_ui5_api` / `get_ui5_api` / `list_ui5_libraries`. Data is bundled offline from the SAPUI5 SDK, pinned to SAP DM's target UI5 version — see `docu/ui5-api-specs/VERSION.md`. No `ui5.yaml` / `webapp/` project shell needed; works from any directory. `get_ui5_api` supports section-slicing (`properties` | `methods` | `events` | `aggregations` | `associations` | `summary`) so a properties-only lookup costs ~2 KB. For coding conventions (bindings, forms, i18n, TS event types) call `get_ui5_guidelines` — POD 2-curated best-practice list.",
  "",
  "> **Related domain rule (UI control choice)**: For every UI control decision, the [Prime Directive — Standard Controls Before Custom](../../../docu/basics.md#§0-prime-directive-standard-controls-before-custom) in `basics.md` §0 governs the choice. The meta-rules govern *how* the agent reasons; the Prime Directive governs *what* it builds. Load `basics.md` §0 alongside these meta-rules for any task that touches widget / action / dialog / property-editor UI.",
  "",
  "**Workspace code** (especially `examples/` and existing project files) is also authoritative — read it with `read_file` / `search_files` instead of inventing.",
  "",
  "### Mandatory verification BEFORE writing code",
  "",
  "The agent MUST verify whenever code uses:",
  "- ❓ A POD2 / SAP DM API class, method, or namespace → `get_api_doc` first",
  '- ❓ A generic UI5 control / property / event → `get_ui5_api({ symbol: "..." })` (or `search_ui5_api` if the class name is unclear) first',
  "- ❓ An import path → verify via `get_api_doc` (POD2) or `get_ui5_api` (UI5) — the `module` field is authoritative",
  '- ❓ A REST endpoint or request/response shape → `get_rest_api({ endpoint: "METHOD /path" })`',
  "- ❓ A pattern (subscribe, dialog, form, table, action lifecycle, …) → `get_pattern_doc`",
  "- ❓ A field on an MDO entity → `get_mdo_entity`",
  "",
  "### Forbidden behaviors",
  "",
  "- ❌ Writing an `sap.ui.define([...])` import that was not verified via MCP",
  "- ❌ Calling `someApi.doX()` without confirming the method in the API docs",
  '- ❌ "I assume POD2 has a method like..." — assumption is not allowed; ASK the MCP server',
  "- ❌ Filling in REST request/response shapes from memory — always pull the OpenAPI spec",
  "- ❌ Copying patterns from generic UI5 / Fiori / training-data knowledge without checking POD2-specifics",
  '- ❌ Skipping `get_ui5_api` for UI5 controls just because "I know sap.m"',
  '- ❌ WebFetching `https://ui5.sap.com/#/api/<Class>` for verification — that URL is an SPA shell, `WebFetch` sees only the page title, not the API. Use `get_ui5_api({ symbol: "..." })` (bundled JSON = same data the SDK loads at runtime).',
  "",
  "### When uncertain — mandatory honesty",
  "",
  "If neither MCP servers nor workspace code contain the answer, the agent MUST say so explicitly and offer a choice:",
  "",
  '> *"I could not find this in the MCP servers or workspace (searched: A, B, C). I can either (a) ask you for clarification, or (b) make an explicit assumption and mark it as such — which do you prefer?"*',
  "",
  "Never paper over a knowledge gap with plausible-sounding invention.",
  "",
  "### Source attribution",
  "",
  '- For non-trivial POD2 / SAP DM / UI5 facts in answers, the agent SHOULD briefly cite the source (e.g. *"per `get_api_doc({ className: "...PodContext" })`"* or *"per UI5 `get_guidelines` §1"*).',
  "- For uncertain or borderline claims, source attribution is **MUST** — without a verifiable source, the claim must be rephrased as an explicit assumption.",
  "",
  "**This makes hallucinations immediately visible: no source → likely invented.**",
].join("\n");
