// Section 1: Architecture Rules, Plugin Types, Widget Subtypes

export const SECTION_ARCHITECTURE = [
  "# POD2 Plugin Development - Essential Guidelines",
  "",
  "## Architecture Rules",
  "1. **Widgets and Actions are independent** - never reference each other directly",
  "2. **Data exchange via PodContext** - `PodContext.set()/get()/subscribe()`",
  "3. **Always unsubscribe** in `onExit()` to prevent memory leaks",
  "4. **Use a Context Singleton** for shared state between Actions and Widgets",
  "5. **Namespaces must NOT start with `sap/`** - use your own (e.g. `myCompany.myProject`)",
  "6. **Namespace = extension.json** - The namespace is defined in extension.json (`modulePath`/`type`), NOT derived from the folder/directory name. The POD framework handles the mapping.",
  "",
  "## Plugin Types",
  "| Type | Base Class | Key Method |",
  "|------|-----------|------------|",
  "| Widget | `sap/dm/dme/pod2/widget/Widget` | `_createView()`, `onInit()`, `onExit()` |",
  "| Action | `sap/dm/dme/pod2/action/Action` | `execute(oActionContext)` |",
  "",
  "## Widget Subtypes",
  "| Subtype | Base Class | Description | Additional Methods |",
  "|---------|-----------|-------------|-------------------|",
  "| ControlWidget | `Widget` | Single control (Button, Input, Text) | - |",
  "| LayoutWidget | `LayoutWidget` | Container for child controls (drag-drop in Designer) | - |",
  "| TableWidget | `Widget` | Data table with selection | `_createColumns()`, `_createTableCells()` |",
  "| ContentHandler | `Widget` | Dialog/form content provider | `_createView()` returns form content |",
  "| ComponentWidget | `ComponentWidget` | SAPUI5 Component-based (own Component.js + MVC) | `getComponentName()`, `getComponentModels()` |",
  "| IntegrationWidget | `IntegrationWidget` | External/iframe integration | `getEntryPoint()`, `ready()` |",
].join("\n");
