// Section 2: Best Practice Pattern, Mandatory Requirements

export const SECTION_BEST_PRACTICE = [
  "## Best Practice Pattern (Phil-style)",
  "",
  "**File layout – flat, directly in the working directory (project root). NO wrapper folder named after the plugin.**",
  "",
  "```",
  "<working directory> / <project root>          ← all files go DIRECTLY here",
  "├── extension.json              ← Plugin registration (MUST be at ZIP root = working directory)",
  "├── README.md                   ← Project documentation (REQUIRED)",
  "├── context/MyContext.js        ← Singleton with static get/set methods",
  "├── widget/MyWidget.js          ← UI component",
  "├── action/MyValidationAction.js ← Checks preconditions (throw Error to stop)",
  "├── action/MyExecutionAction.js  ← Business logic (API calls)",
  "└── i18n/ (4 files: .properties, _de, _en, _en_US)",
  "```",
  "",
  "> ⚠️ **No wrapper folder**: Do NOT create a `<PluginName>/` subdirectory inside the working directory. The folders `widget/`, `action/`, `context/`, `i18n/` and the file `extension.json` must live **directly in the working directory (= project root = ZIP root)**. The `modulePath` in `extension.json` is a UI5 *logical* module name – it does NOT need to match the physical folder layout.",
  "",
  "## Mandatory Requirements",
  "- **Flat layout**: All files (extension.json, README.md) and folders (widget/, action/, context/, i18n/) directly in the working directory – no `<PluginName>/` wrapper",
  "- **README.md**: Always generate in the style of the examples (use `get_example` to see Customer.Coating/README.md as reference)",
  "- **i18n**: Always provide 4 locale files",
  "- **ES6 classes** with `sap.ui.define` module loading",
  '- **I18nResourceModel** for static i18n: `static #oI18nModel = new I18nResourceModel("ns.i18n.i18n")`',
  '- **Logger** instead of `console.log`: `Logger.getLogger("myCompany.MyPlugin")`',
  "- **Static metadata methods**: `getDisplayName()`, `getDescription()`, `getIcon()`, `getCategory()`",
  '- **i18nCustomModel in onInit()**: Register the i18n model on the POD view in `widget.onInit()`: `let i18nCustomModel = MyWidget.getI18nModel(); this.getPodRuntime().getView().setModel(i18nCustomModel, "i18nMyWidget");` — model name is `"i18n"` + PascalCase widget short name (e.g. `i18nCoating`); multi-widget plugins register one model per widget (`i18nCoating` AND `i18nHelloWorld` side-by-side).',
  "- **Form Layout**: Use `sap/ui/layout/form/Form`, `FormContainer`, `FormElement`, `ResponsiveGridLayout` for well-formed UIs",
].join("\n");
