// Section 3: Backend API Call Patterns (PPD + RestClient)

export const SECTION_API_PATTERNS = [
  "## Backend API Calls – Two Patterns",
  "",
  "### Option 1: Production Process (PPD) via ApiClient",
  "Use when triggering business logic via Production Process Designer.",
  "**Best Practice:** Store the PPD key as an Action/Widget Property (configurable in POD Designer via `StringPropertyEditor`).",
  "```javascript",
  "import ApiClient from 'sap/dm/dme/pod2/api/ApiClient';",
  "// PPD key from Action property (configured in POD Designer)",
  "const ppd = this.getPropertyValue('productionProcess');",
  "if (!ppd) throw new Error('PPD key not configured');",
  "await ApiClient.internal.processengine.start({",
  "    key: ppd,",
  "    async: false,",
  "    triggerFrom: 'pod',",
  "    passUserId: true,",
  "    sourceName: 'MyExecutionAction',",
  "    parameters: {",
  "        Plant: PodContext.getPlant(),",
  "        Workcenter: PodContext.getFilterWorkCenters()?.[0]?.workCenter,",
  "        Resource: PodContext.getFilterResources()?.[0]?.resource,",
  "        Sfcs: [{ Sfc: '...', Weight: 123 }]",
  "    }",
  "});",
  "```",
  "→ Define the PPD key property via `getProperties()` + `ActionProperty` + `StringPropertyEditor`",
  "",
  "### Option 2: RestClient + ApiPaths (Direct REST API)",
  "Use for direct CRUD operations against SAP DM Public REST APIs:",
  "```javascript",
  "import RestClient from 'sap/dm/dme/pod2/api/RestClient';",
  "import ApiPaths from 'sap/dm/dme/pod2/api/ApiPaths';",
  "const sUrl = ApiPaths.API_GATEWAY_MS_PATH + '/sfc/v1/sfcData';",
  "const oResult = await RestClient.get(sUrl, { plant: PodContext.getPlant(), sfc: '...' });",
  "```",
  "→ Full pattern: `get_pattern_doc({ name: 'pod2-public-api-pattern' })`",
  "",
  "### When to use which?",
  "| Use Case | Pattern |",
  "|----------|---------|",
  "| Trigger PPD business logic | `ApiClient.internal.processengine.start()` |",
  "| Read/Write SAP DM REST APIs directly | `RestClient` + `ApiPaths` |",
  "| PPD key storage | Action Property (`StringPropertyEditor`) |",
  "| Custom microservice calls | `RestClient` with custom relative path |",
  "",
  "### ⚠️ Public-API-First — internal / app-router APIs need explicit confirmation",
  "**Always solve a plugin requirement with the PUBLIC SAP DM REST APIs first** (the services in `list_rest_apis` / `get_rest_api`, reached via `RestClient` + `ApiPaths`, or the typed `*PublicApiClient`s / `ApiClient.<domain>`).",
  "",
  "Do **NOT** hard-wire *internal / app-router* endpoints into plugin source — a URL on an execution host (`*.execution.*.web.dmc.cloud.sap`), a `~GUID~` path segment, or a `dmi/cdt` / `dim/destinations` service prefix. These are unversioned, per-deployment surfaces that the Fiori UIs use internally; they break across tenants and releases.",
  "",
  "If (and only if) no public API can satisfy the requirement:",
  "1. Say so explicitly and name the public services you checked.",
  "2. Present the internal call you would make and **ask the user for explicit confirmation** before writing it into the plugin. Silence is not consent.",
  "",
  "> **Not the same thing:** `ApiClient.internal.processengine.start(...)` (Option 1 above) is a **documented POD2 framework API** for triggering a Production Process — it is fully allowed and is NOT what this rule restricts. The rule targets raw calls to app-router / DMI execution hosts (the surface the `sap-dm-api-mcp-server` `call_internal_api` tool queries — that tool is for agent-side discovery, its results are not plugin code).",
].join("\n");