// Section 4: Key APIs + Critical Import Paths

export const SECTION_KEY_APIS = [
  "## Key APIs",
  "- `PodContext` - Global state management (get/set/subscribe)",
  "- `PodRuntime` - Navigation, widget lookup, dialog management (via `this.getPodRuntime()`)",
  "- `ApiClient` - Typed API access (`.sfc`, `.order`, `.material`, `.internal.processengine`, etc.)",
  "- `RestClient` - Direct REST calls (auto-handles auth, CSRF, App Router prefix)",
  "- `SfcPublicApiClient` - SFC operations (start, complete, signoff, split, merge)",
  "- `OrderPublicApiClient` - Order data + custom fields",
  "- `MaterialPublicApiClient` - Material master data",
  "- `OperationActivityPublicApiClient` - Operation activities",
  "- `UserPublicApiClient` - Current user info",
  "- `DataFieldsPublicApiClient` - Data field options",
  "- `ExecutionPublicApiClient` - Execution operations",
  "- `NumberFormatter` / `StringFormatter` - Locale-aware display formatting",
  "- `PodNotificationWebSocket` - Real-time server-push events (subscribe to plant events)",
  "- `ActionRegistry` / `WidgetRegistry` - Programmatic plugin discovery",
  "- Use `get_api_doc` for full method documentation",
  "",
  "## Critical Import Paths",
  '- PodContext: `"sap/dm/dme/pod2/context/PodContext"`',
  '- Widget: `"sap/dm/dme/pod2/widget/Widget"`',
  '- LayoutWidget: `"sap/dm/dme/pod2/widget/LayoutWidget"`',
  '- ComponentWidget: `"sap/dm/dme/pod2/widget/ComponentWidget"` (Component-based)',
  '- IntegrationWidget: `"sap/dm/dme/pod2/widget/IntegrationWidget"` (iframe/external)',
  '- Action: `"sap/dm/dme/pod2/action/Action"`',
  '- Logger: `"sap/dm/dme/pod2/Logger"`',
  '- RestClient: `"sap/dm/dme/pod2/api/RestClient"`',
  '- ApiClient: `"sap/dm/dme/pod2/api/ApiClient"`',
  '- ApiPaths: `"sap/dm/dme/pod2/api/ApiPaths"` (internal, undocumented — constants like API_GATEWAY_MS_PATH, PLANT_MS_PATH)',
  '- PodRuntime: accessed via `this.getPodRuntime()` (NOT imported directly)',
  '- NumberFormatter: `"sap/dm/dme/pod2/formatter/NumberFormatter"`',
  '- PodDialog: `"sap/dm/dme/pod2/control/PodDialog"`',
  "",
  "## SAPUI5 Enum Imports (IMPORTANT — deprecated pseudo-modules!)",
  "Since recent SAPUI5 versions, importing enum types directly is DEPRECATED:",
  '- ❌ `import ListSeparators from "sap/m/ListSeparators"` — DEPRECATED',
  '- ✅ `import library from "sap/m/library"; const { ListSeparators } = library;`',
  "This applies to ALL enum-type modules: ListSeparators, ButtonType, ListMode, ListType,",
  "PlacementType, FlexAlignItems, ValueState, MessageType, TextAlign, etc.",
  '- UI5 enums from `sap/m/`: import `"sap/m/library"` then destructure',
  '- UI5 enums from `sap/ui/core/`: import `"sap/ui/core/library"` then destructure',
  '- Form: `"sap/ui/layout/form/Form"`',
  '- FormContainer: `"sap/ui/layout/form/FormContainer"`',
  '- FormElement: `"sap/ui/layout/form/FormElement"`',
  '- ResponsiveGridLayout: `"sap/ui/layout/form/ResponsiveGridLayout"`',
].join("\n");
