// Section 5: Complete Tool Catalog

export interface ContentCounts {
  patternDocs: number;
  apiClasses: number;
  restApis: number;
  examples: number;
}

export function buildToolCatalog(c: ContentCounts): string {
  return [
    "## RECOMMENDED FIRST STEPS",
    "",
    "Before generating any code, follow this discovery sequence:",
    "",
    "1. **Step 0** – `get_example({ plugin: 'Customer.HelloWorld' })` for a minimal widget OR `get_example({ plugin: 'Customer.Coating' })` for the full Best-Practice template.",
    "2. `get_pattern_doc({ name: 'basics' })` – read Section 0 (Namespace Cheatsheet) and Section 12 (Best-Practice Pattern).",
    "3. Load common-mistakes by category — avoid documented pitfalls before writing code:",
    "   `common-mistakes-setup`, `common-mistakes-lifecycle`, `common-mistakes-imports`, `common-mistakes-ui`, `common-mistakes-config`, `common-mistakes-data`, `common-mistakes-i18n`",
    "4. For the specific widget subtype: `get_pattern_doc({ name: 'widget-patterns-core', section: '<subtype>' })` or `summary: true` first to see the TOC.",
    "",
    "## COMPLETE TOOL CATALOG (19 Tools)",
    "",
    "### Quick Start Tools",
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `get_pod2_guidelines` | (none) | This tool - call once at start |",
    "| `list_capabilities` | (none) | Full server capabilities overview |",
    "",
    `### Pattern Documentation (${c.patternDocs} docs)`,
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `list_pattern_docs` | (none) | List all pattern docs with descriptions |",
    "| `get_pattern_doc` | `name`: string, `section`?: string, `summary`?: bool | Read a specific doc. Use `summary: true` for TOC before loading a large file. |",
    "| `search_docs` | `query`: string | Full-text search across pattern docs |",
    "",
    `### POD2 API Reference (${c.apiClasses} classes)`,
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `get_api_index` | `filter`?: string | API index (all namespaces & classes). Use filter to narrow, e.g. `filter: 'widget'`. |",
    "| `get_api_doc` | `name`: string | Class doc – accepts full path or short aliases (`Widget`, `PodContext`, `SfcClient`, …). |",
    "| `list_api_docs` | `filter`?: string, `offset`?: number, `limit`?: number | List classes, optionally filtered by namespace |",
    "| `search_api_docs` | `query`: string | Search across all API docs |",
    "",
    `### SAP DM REST APIs (${c.restApis} OpenAPI specs)`,
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `list_rest_apis` | (none) | List all available REST API specs |",
    "| `get_rest_api` | `serviceName`: string, `summary`?: bool | Get OpenAPI spec for a service |",
    "| `search_rest_apis` | `query`: string | Search endpoints across all APIs |",
    "",
    "### MDO Extractor (OData V4 entities for analytics/reporting)",
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `list_mdo_entities` | (none) | List all MDO entities (ORDER, SFC, MATERIAL, ROUTING, BOM, …) with property/navigation counts |",
    "| `get_mdo_entity` | `entityName`: string | Full property list + types + key fields for one entity (case-insensitive) |",
    "| `search_mdo_entities` | `query`: string | Search across all entity property names and types |",
    "",
    `### Reference Examples (${c.examples} plugins)`,
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `list_examples` | (none) | List all reference example plugins with file structure |",
    "| `get_example` | `plugin`: string, `file`?: string | Read source code from a reference plugin |",
    "",
    "### Cross-Search & Validation",
    "| Tool | Parameters | Description |",
    "|------|-----------|-------------|",
    "| `search_all` | `query`: string, `mode`?: 'any'|'all' | Search across ALL content areas (TF-IDF scored) |",
    "| `validate_project` | (none) | Full plugin validation → VALIDATION-REPORT.md |",
    "",
    "### Code Generation Prompts (5)",
    "| Prompt | Key Parameters |",
    "|--------|---------------|",
    "| `create_widget` | namespace, widgetName, widgetType? |",
    "| `create_action` | namespace, actionName, actionType |",
    "| `create_extension` | namespace, pluginName (generates 10 files) |",
    "| `migrate_widget` | sourceDir — 5-phase migration with feature-loss prevention |",
    "| `validate_project` | (none) — same workflow as the tool |",
    "",
    "### MCP Resources (optional, advanced)",
    "| Resource URI | What it exposes |",
    "|--------------|-----------------|",
    "| `pod2://patterns/{name}` | Any pattern doc by name |",
    "| `pod2://api/{className}` | Individual API class doc |",
    "| `pod2://rest-api/{serviceName}` | OpenAPI JSON spec |",
  ].join("\n");
}
