// Section 6: REST Services, Usage Examples, Key Pattern Docs, Reference Examples

export const SECTION_REST_SERVICES = [
  "## AVAILABLE REST API SERVICES (use with get_rest_api)",
  "",
  "**Production**: sfc, order, operationactivity, assembly, activityConfirmation, quantityConfirmation, production_v2",
  "**Material**: material, bom, routing, batch, materialgroup",
  "**Process Mfg**: processorder, processlot, process_manufacturing, recipe, setpoint_v3, reo",
  "**Inventory**: inventory, staging, logistics, packingunit, wip",
  "**Quality**: datacollection, qualityinspection, nonconformance, nonconformancecode, nonconformancegroup, ebr, classification",
  "**Config**: plant, resourcetype, tool, shift, user, pod, uom, numbering, standardrate, standardvalue, labor, timetracking, asset_model, oee",
  "**Integration**: workinstruction, workinstruction_file, notification, integrationMessage",
  "**Foundation**: print (sapfnd), printer (sapfnd), document_v2 (sapfnd), signature (sapfnd)",
  "**Analytics**: alerts, issues, psp, oee",
  "",
  "### Usage Examples:",
  '- Process Lots API: `get_rest_api({ serviceName: "processlot" })`',
  '- Order API summary: `get_rest_api({ serviceName: "order", summary: true })`',
  '- Find SFC endpoints: `search_rest_apis({ query: "start" })`',
  '- Widget base class: `get_api_doc({ name: "sap.dm.dme.pod2.widget.Widget" })`',
  '- Table patterns: `get_pattern_doc({ name: "tablecell-patterns" })`',
  '- Reference code: `get_example({ plugin: "Customer.Coating" })`',
  "",
  "## Key Pattern Docs (use get_pattern_doc)",
  "- `extension-json-schema` - **MUST READ** – extension.json schema, naming rules, file structure",
  "- `subscribe-patterns` - **MUST READ** – ModelPath, isRunMode(), PodContext subscribe/unsubscribe lifecycle",
  "- `property-editors` - **MUST READ** – PropertyEditor types (String, Boolean, Enum), WidgetProperty vs ActionProperty",
  "- `pod2-public-api-pattern` - REST API calling (RestClient + ApiPaths) - **MUST READ for any direct API call**",
  "- `widget-patterns-core` - Core widget type templates (ControlWidget, LayoutWidget, TableWidget, ContentHandler, i18n)",
  "- `widget-patterns-advanced` - Advanced patterns (API integration, pagination, cells, ComponentWidget)",
  "- `advanced-patterns` - 11 advanced enterprise patterns",
  "- `common-mistakes` - 28 documented mistakes with fixes",
  "- `form-patterns` - Form validation patterns",
  "- `binding-patterns` - Data binding and formatters",
  "- `tablecell-patterns` - 13 table cell types",
  "- `mdo-extractor-reference` - MDO OData V4 entity reference (ORDER, SFC, MATERIAL, ROUTING, BOM, NON_CONFORMANCE, OEE, DOWNTIME, …)",
  "- `PATTERN-INDEX` - Quick-reference index by use case and complexity",
  "",
  "## Reference Examples (use list_examples / get_example)",
  "- `Customer.Coating` - Full Best Practice plugin (Widget + Validation + Execution + Context + i18n)",
  "- `Customer.TableView` - Widget with PodContext subscribe, dynamic table rendering via PPD",
  "- `Customer.Utils` - Standalone Action with EnumPropertyEditor",
].join("\n");
